### ISSUE TITLE
Question text animation does not reset when new questions are loaded

### ISSUE THREAD

**Issue by isaiahfisher** [isaiahfisher/UntitledQuizGame#6]
## Summary of issue
Currently, the question text animation is a console type animation where the question is 'typed' by the application into the browser, appearing similar to how lines of code are typed on a terminal. 

This issue documents the known problem where question animations are not reset when a user navigates to the next question.

## Expected behavior:
When a user navigates to the next question, the text animation will restart, typing in the next question from the start.

## Current behavior:
When a user navigates to any question, the current cursor position in the animation is retained and the text is changed to reflect the new question

## Reproduction guide:
1) Register user to the application
2) create _**at least 10**_ questions using the question upload form
3) begin a quiz
4) take the quiz, paying special attention to the question text and its animation

**Comment by naquib555** [comment]
Text animation reset issue fixed and PR merged: https://github.com/isaiahfisher/UntitledQuizGame/pull/new/issue6
